In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
cars = pd.read_csv('car_data.csv')
cars.head()

speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         NaN    60
4    140        5         3.0    82

In [3]:
cars.isnull().sum()

speed         0
car_age       0
experience    1
risk          0
dtype: int64

In [4]:
cars.experience

0     5.0
1    13.0
2     4.0
3     NaN
4     3.0
5     8.0
Name: experience, dtype: float64

In [5]:
fill_exp = cars.experience.median()
fill_exp

5.0

In [6]:
cars.experience = cars.experience.fillna(fill_exp)

In [7]:
cars.experience

0     5.0
1    13.0
2     4.0
3     5.0
4     3.0
5     8.0
Name: experience, dtype: float64

In [8]:
cars

speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         5.0    60
4    140        5         3.0    82
5    115        2         8.0    10

In [9]:
reg = LinearRegression()

In [10]:
reg.fit(cars[['speed', 'car_age', 'experience']], cars.risk)

LinearRegression()

In [11]:
reg.predict([[160,10,5]])

/home/kazi/.local/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([71.37146872])

In [12]:
reg.coef_

array([ 0.33059217,  1.61053246, -6.20772074])

In [13]:
reg.intercept_

33.41000091043592

In [14]:
0.33059217 * 160 + 1.61053246*10 + (-6.20772074 * 5) + 33.41000091043592

71.37146901043593

In [15]:
online_df = pd.read_csv("online.csv")
online_df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [16]:
online_df.shape

(50, 5)

In [17]:
online_df.isnull().sum()

Marketing Spend    0
Administration     0
Transport          0
Area               0
Profit             0
dtype: int64

In [18]:
# handle null value, if has
# mean = online_df.Administration.mean()
# online_df.Administration = online_df.Administration.fillna(mean)

In [19]:
# seprate x and y
x = online_df.drop(['Profit'], axis=1)
x.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [20]:
y = online_df['Profit']
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [21]:
# one hot encoding
cities = pd.get_dummies(x['Area'], drop_first=True)
cities

Dhaka  Rangpur
0       1        0
1       0        0
2       0        1
3       1        0
4       0        1
5       1        0
6       0        0
7       0        1
8       1        0
9       0        0
10      0        1
11      0        0
12      0        1
13      0        0
14      0        1
15      1        0
16      0        0
17      1        0
18      0        1
19      1        0
20      0        0
21      1        0
22      0        1
23      0        1
24      1        0
25      0        0
26      0        1
27      1        0
28      0        1
29      1        0
30      0        1
31      1        0
32      0        0
33      0        1
34      0        0
35      1        0
36      0        1
37      0        0
38      1        0
39      0        0
40      0        0
41      0        1
42      0        0
43      1        0
44      0        0
45      1        0
46      0        1
47      0        0
48      1        0
49      0        0

In [22]:
x = x.drop('Area', axis=1)

In [23]:
#Concat two data frame
x = pd.concat([x,cities], axis=1)
x

Marketing Spend  Administration  Transport  Dhaka  Rangpur
0         114523.61       136897.80  471784.10      1        0
1         162597.70       151377.59  443898.53      0        0
2         153441.51       101145.55  407934.54      0        1
3         144372.41       118671.85  383199.62      1        0
4         142107.34        91391.77  366168.42      0        1
5         131876.90        99814.71  362861.36      1        0
6         134615.46       147198.87  127716.82      0        0
7         130298.13       145530.06  323876.68      0        1
8         120542.52       148718.95  311613.29      1        0
9         123334.88       108679.17  304981.62      0        0
10        101913.08       110594.11  229160.95      0        1
11        100671.96        91790.61  249744.55      0        0
12         93863.75       127320.38  249839.44      0        1
13         91992.39       135495.07  252664.93      0        0
14        119943.24       156547.42  256512.92      0        1
15        165349.20       122616.84  261776.23      1        0
16         78013.11       121597.55  264346.06      0        0
17         94657.16       145077.58  282574.31      1        0
18         91749.16       114175.79  294919.57      0        1
19         86419.70       153514.11       0.00      1        0
20         76253.86       113867.30  298664.47      0        0
21         78389.47       153773.43  299737.29      1        0
22         73994.56       122782.75  303319.26      0        1
23         67532.53       105751.03  304768.73      0        1
24         77044.01        99281.34  140574.81      1        0
25         64664.71       139553.16  137962.62      0        0
26         75328.87       144135.98  134050.07      0        1
27         72107.60       127864.55  353183.81      1        0
28         66051.52       182645.56  118148.20      0        1
29         65605.48       153032.06  107138.38      1        0
30         61994.48       115641.28   91131.24      0        1
31         61136.38       152701.92   88218.23      1        0
32         63408.86       129219.61   46085.25      0        0
33         55493.95       103057.49  214634.81      0        1
34         46426.07       157693.92  210797.67      0        0
35         46014.02        85047.44  205517.64      1        0
36         28663.76       127056.21  201126.82      0        1
37         44069.95        51283.14  197029.42      0        0
38         20229.59        65947.93  185265.10      1        0
39         38558.51        82982.09  174999.30      0        0
40         28754.33       118546.05  172795.67      0        0
41         27892.92        84710.77  164470.71      0        1
42         23640.93        96189.63  148001.11      0        0
43         15505.73       127382.30   35534.17      1        0
44         22177.74       154806.14   28334.72      0        0
45          1000.23       124153.04    1903.93      1        0
46          1315.46       115816.21  297114.46      0        1
47             0.00       135426.92       0.00      0        0
48           542.05        51743.15       0.00      1        0
49             0.00       116983.80   45173.06      0        0

In [24]:
# split dataset into train and test
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=.25,random_state=0)

# create linear reg object
reg  = LinearRegression()

In [25]:
reg.fit(xtrain,ytrain)

LinearRegression()

In [26]:
ytest

28    103282.38
11    144259.40
10    146121.95
41     77798.83
2     191050.39
27    105008.31
38     81229.06
31     97483.56
22    110352.25
4     166187.94
33     96778.92
35     96479.51
26    105733.54
Name: Profit, dtype: float64

In [27]:
# predict
pred = reg.predict(xtest)
pred

array([103501.0825284 , 128011.28068627, 126695.43891127,  70573.91718775,
       173381.96874259, 124238.07860872,  69298.09250304,  98399.41936876,
       116419.1480864 , 161430.98134847,  94740.73303076,  89920.22800514,
       105956.86065332])

In [29]:
reg.score(xtest, ytest)

0.8840978623923472

In [28]:
r2_score(ytest,pred)

0.8840978623923472