In [1]:
import numpy as np

In [2]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [3]:
y = np.arange(2,12,2)
y

array([ 2,  4,  6,  8, 10])

In [4]:
print(x*y)

[ 2  8 18 32 50]


In [5]:
x = np.asmatrix(np.arange(1,6))
x

matrix([[1, 2, 3, 4, 5]])

In [6]:
y = np.asmatrix(np.arange(2,12,2))
y

matrix([[ 2,  4,  6,  8, 10]])

In [8]:
np.multiply(x,y)

matrix([[ 2,  8, 18, 32, 50]])

In [9]:
np.transpose(y)

matrix([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]])

In [10]:
y.transpose()

matrix([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]])

In [11]:
y.T

matrix([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]])

In [12]:
np.dot(x,y.T)

matrix([[110]])

In [13]:
x @ y.T

matrix([[110]])

In [14]:
a1 = np.array([[1, 2, 3], [4, 5, 6]]) 
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a2 = np.arange(1,7).reshape(2,3)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a3 = np.zeros([3,3])
a3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
a4 = np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
a5 = np.random.rand(2,3)
a5

array([[0.44988968, 0.13165798, 0.95214583],
       [0.83548029, 0.00360557, 0.6739239 ]])

In [19]:
a6 = a1.copy()
a6

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a7 = a1 
a7

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
m1 = np.matrix('1 2 3; 4 5 6; 7 8 9')
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
m2 = np.asmatrix(a1.copy())
m2

matrix([[1, 2, 3],
        [4, 5, 6]])

In [23]:
m3 = np.mat(np.array([1, 2, 3]))
m3

matrix([[1, 2, 3]])

In [24]:
a8 = np.asarray(m1)
a8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
m = np.matrix('1 2 3; 4 5 6; 7 8 9')
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
m[0,0]

1

In [27]:
m[-1,-1]

9

In [28]:
m[0,:]

matrix([[1, 2, 3]])

In [31]:
m[:,1]

matrix([[2],
        [5],
        [8]])

In [32]:
m[1:3,-1]

matrix([[6],
        [9]])

In [33]:
m[-1,-1] = 10000
m[0:2,-1] = np.matrix('100; 1000')
m[:,0] = 0

In [34]:
m2[m2>0.5]

matrix([[1, 2, 3, 4, 5, 6]])

In [35]:
m2[m2<0.5] = 0

In [36]:
m1 = 10 * np.mat(np.ones([3,3]))
m1

matrix([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])

In [37]:
m2 = np.mat(np.random.rand(3,3))
m2

matrix([[0.31609235, 0.29406265, 0.28003496],
        [0.22850099, 0.70855827, 0.46486953],
        [0.87168016, 0.72204926, 0.37234661]])

In [38]:
m1+m2  

matrix([[10.31609235, 10.29406265, 10.28003496],
        [10.22850099, 10.70855827, 10.46486953],
        [10.87168016, 10.72204926, 10.37234661]])

In [39]:
m1*m2

matrix([[14.16273497, 17.24670182, 11.17251097],
        [14.16273497, 17.24670182, 11.17251097],
        [14.16273497, 17.24670182, 11.17251097]])

In [40]:
np.multiply(m1,m2)

matrix([[3.1609235 , 2.94062652, 2.80034958],
        [2.2850099 , 7.08558272, 4.64869528],
        [8.71680157, 7.22049259, 3.72346611]])

In [41]:
m1>m2 

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [43]:
m3 = np.hstack((m1,m2))
m3

matrix([[10.        , 10.        , 10.        ,  0.31609235,  0.29406265,
          0.28003496],
        [10.        , 10.        , 10.        ,  0.22850099,  0.70855827,
          0.46486953],
        [10.        , 10.        , 10.        ,  0.87168016,  0.72204926,
          0.37234661]])

In [44]:
m4 = np.vstack((m1,m2))
m4

matrix([[10.        , 10.        , 10.        ],
        [10.        , 10.        , 10.        ],
        [10.        , 10.        , 10.        ],
        [ 0.31609235,  0.29406265,  0.28003496],
        [ 0.22850099,  0.70855827,  0.46486953],
        [ 0.87168016,  0.72204926,  0.37234661]])

In [45]:
m3.shape

(3, 6)

In [46]:
m3.mean()

5.236566376489568

In [47]:
m3.mean(axis=0)

matrix([[10.        , 10.        , 10.        ,  0.47209117,  0.57489006,
          0.37241703]])

In [48]:
m3.mean(axis=1)

matrix([[5.14836499],
        [5.2336548 ],
        [5.32767934]])

In [49]:
m3.transpose()

matrix([[10.        , 10.        , 10.        ],
        [10.        , 10.        , 10.        ],
        [10.        , 10.        , 10.        ],
        [ 0.31609235,  0.22850099,  0.87168016],
        [ 0.29406265,  0.70855827,  0.72204926],
        [ 0.28003496,  0.46486953,  0.37234661]])

In [50]:
m2.I     

matrix([[ 1.29839414, -1.67575707,  1.11566116],
        [-5.78680202,  2.28490633,  1.49947258],
        [ 8.18208522, -0.50783525, -2.83389919]])