In [1]:
import numpy as np

In [3]:
a = np.zeros(2)
print(a)

[0. 0.]


In [4]:
print(np.arange(0, 3.6, 0.6))

[0.  0.6 1.2 1.8 2.4 3. ]


In [5]:
print(np.ones(3))

[1. 1. 1.]


In [6]:
x = np.concatenate([np.zeros(2), np.arange(0, 3.6, 0.6), np.ones(3)])
print(x)

[0.  0.  0.  0.6 1.2 1.8 2.4 3.  1.  1.  1. ]


In [7]:
x[1:5]

array([0. , 0. , 0.6, 1.2])

In [8]:
np.size(x)

11

In [9]:
len(x)

11

In [10]:
x[-1]

1.0

In [11]:
x[1::2]

array([0. , 0.6, 1.8, 3. , 1. ])

In [13]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lst[2::2]

[3, 5, 7, 9]

In [16]:
y = x;
y

array([0.        , 3.14159265, 0.        , 3.14159265, 1.2       ,
       3.14159265, 2.4       , 3.14159265, 1.        , 3.14159265,
       1.        ])

In [17]:
y[1::2]  = np.pi