In [1]:
import numpy as np
import xlrd

In [2]:
doc = xlrd.open_workbook('data/nanonose.xls').sheet_by_index(0)
doc

Sheet  0:<Sheet1>

In [4]:
attributeNames = doc.row_values(0, 3, 11)
attributeNames

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [11]:
classLabels = doc.col_values(0, 2, 92)
classLabels

['Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Water',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Ethanol',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Acetone',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Heptane',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'Pentanol',
 'P

In [12]:
classNames = sorted(set(classLabels))
classNames

['Acetone', 'Ethanol', 'Heptane', 'Pentanol', 'Water']

In [13]:
classDict = dict(zip(classNames, range(5)))
classDict

{'Acetone': 0, 'Ethanol': 1, 'Heptane': 2, 'Pentanol': 3, 'Water': 4}

In [14]:
y = np.asarray([classDict[value] for value in classLabels])
y

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3])

In [17]:
X = np.empty((90, 8))
X

array([[4.04738577e-320, 2.88534337e-321, 0.00000000e+000,
        4.65862567e-310, 4.94065646e-324, 4.65862567e-310,
        4.65862567e-310, 4.94065646e-324],
       [4.65862567e-310, 4.65862567e-310, 1.18575755e-322,
        6.94154389e-310, 4.65841736e-310, 0.00000000e+000,
        4.94065646e-324, 2.12199579e-314],
       [1.18575755e-322, 6.94154196e-310, 4.94065646e-324,
        2.12199579e-314, 8.48798316e-314, 1.27319747e-313,
        1.03753786e-322, 4.65862567e-310],
       [6.94154389e-310, 2.12199579e-314, 8.48798316e-314,
        2.54639495e-313, 4.94065646e-324, 4.65862567e-310,
        4.65862567e-310, 9.88131292e-324],
       [4.65862567e-310, 4.65862567e-310, 4.65862567e-310,
        4.65841736e-310, 6.94154407e-310, 0.00000000e+000,
        6.94147263e-310, 2.97079411e-313],
       [3.39519327e-313, 4.65841736e-310, 6.94154407e-310,
        0.00000000e+000, 6.94147263e-310, 3.81959242e-313,
        4.03179200e-313, 6.94147263e-310],
       [6.94150732e-310, 0.0000000

In [18]:
for i, col_id in enumerate(range(3, 11)):
    X[:, i] = np.asarray(doc.col_values(col_id, 2, 92))
X

array([[ 9.55000000e+01,  2.10000000e+01,  6.00000000e+00,
         1.19423077e+01,  6.41346154e+01,  2.14985600e+01,
         5.56784000e+00,  1.17413500e+00],
       [ 9.45000000e+01,  1.70000000e+01,  5.00000000e+00,
         5.48461538e+00,  6.32057692e+01,  1.96585600e+01,
         4.96800000e+00,  1.88344390e+00],
       [ 9.20000000e+01,  1.60000000e+01,  3.00000000e+00,
         1.10576923e+01,  6.25865385e+01,  1.98131200e+01,
         5.19248000e+00,  5.64834677e-01],
       [ 5.30000000e+01,  7.50000000e+00,  2.50000000e+00,
         3.53846154e+00,  3.51634615e+01,  6.87620690e+00,
         1.64172414e+00,  1.44654088e-01],
       [ 5.10000000e+01,  7.50000000e+00,  2.50000000e+00,
         4.86538462e+00,  3.40576923e+01,  6.75724138e+00,
         1.61396552e+00,  5.96627756e-02],
       [ 5.00000000e+01,  8.00000000e+00,  2.50000000e+00,
         3.98076923e+00,  3.36153846e+01,  6.77310345e+00,
         1.77655172e+00,  7.55088641e-02],
       [ 2.75000000e+01,  4.000000

In [19]:
N = len(y)
N

90

In [20]:
M = len(attributeNames)

In [21]:
C = len(classNames)
C

5