In [1]:
import numpy as np
import xlrd

In [2]:
doc = xlrd.open_workbook('data/iris.xls').sheet_by_index(0)
doc

Sheet  0:<Sheet1>

In [3]:
attributeNames = doc.row_values(0,0,4)
attributeNames

['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width']

In [4]:
classLabels = doc.col_values(4,1,151)
classLabels

['Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',


In [5]:
classNames = sorted(set(classLabels))
classNames

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

In [6]:
classDict = dict(zip(classNames,range(len(classNames))))
classDict

{'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}

In [7]:
y = np.array([classDict[value] for value in classLabels])
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
X = np.empty((150,4))
X

array([[6.92304495e-310, 6.92304495e-310, 4.66982799e-310,
        4.66982799e-310],
       [4.94065646e-324, 4.66982799e-310, 4.66982799e-310,
        4.94065646e-324],
       [4.66982799e-310, 4.66982799e-310, 1.18575755e-322,
        6.92304480e-310],
       [4.66966394e-310, 0.00000000e+000, 4.94065646e-324,
        2.12199579e-314],
       [1.18575755e-322, 6.92304286e-310, 4.94065646e-324,
        2.12199579e-314],
       [8.48798316e-314, 1.27319747e-313, 1.03753786e-322,
        4.66982799e-310],
       [6.92304480e-310, 2.12199579e-314, 8.48798316e-314,
        2.54639495e-313],
       [4.94065646e-324, 4.66982799e-310, 4.66982799e-310,
        9.88131292e-324],
       [4.66982799e-310, 4.66982799e-310, 4.66982799e-310,
        4.66966394e-310],
       [6.92304496e-310, 0.00000000e+000, 6.92279907e-310,
        2.97079411e-313],
       [3.60739284e-313, 4.66966394e-310, 6.92304496e-310,
        0.00000000e+000],
       [6.92279907e-310, 3.81959242e-313, 4.03179200e-313,
      

In [9]:
for i in range(4):
    X[:,i] = np.array(doc.col_values(i,1,151)).T

In [10]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
N = len(y)
N

150

In [13]:
M = len(attributeNames)
M

4

In [14]:
C = len(classNames)
C

3