In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('data/homeprices_mul.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.shape

(6, 4)

In [5]:
df.isnull()

area  bedrooms    age  price
0  False     False  False  False
1  False     False  False  False
2  False      True  False  False
3  False     False  False  False
4  False     False  False  False
5  False     False  False  False

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      6 non-null      int64  
 1   bedrooms  5 non-null      float64
 2   age       6 non-null      int64  
 3   price     6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 320.0 bytes


In [7]:
df.isna()

area  bedrooms    age  price
0  False     False  False  False
1  False     False  False  False
2  False      True  False  False
3  False     False  False  False
4  False     False  False  False
5  False     False  False  False

In [8]:
df.isna().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

# Data Preprocessing: Fill NA values with median value of a column

In [9]:
df.bedrooms.median()

4.0

In [10]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

# Train Model

In [12]:
rg = linear_model.LinearRegression()
rg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [14]:
rg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
rg.intercept_

221323.00186540396

In [18]:
rg.predict([[3000, 3, 40]])

/home/kazi/.local/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [20]:
rg.predict([[2500, 4, 5]])

/home/kazi/.local/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [ ]:
plt.scatter(df['Mileage'], df['Sell Price($)'])
plt.title('Car Prices')
plt.xlabel('Mileage')
plt.ylabel('Sell Price($)')
plt.show()